### PR TITLE
Content change/check answers

### PR DESCRIPTION
**Pull request by murrayholmes96**

### CODE REVIEW

**Review by JohnJAMoore — APPROVED** [review]
LGTM 👍

**Review by JohnJAMoore — CHANGES_REQUESTED** [review]
Lint errors on this PR i have assigned this to paul as my dev env has bombed

**Comment by murrayholmes96** [comment]
i ran this locally and didnt have any lint errors? @JohnJAMoore

**Review by paulcoxsnh — CHANGES_REQUESTED** [review]
Hate to be a pedant, but the confirm page doesn't match the prototype screenshot in https://github.com/Scottish-Natural-Heritage/Licensing/issues/1207.

The tables on the page should be enclosed in:
```
<div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
```
And the text around the declaration checkbox is different in the prototype screenshot.

**Review by JohnJAMoore — APPROVED** [review]

**Review by paulcoxsnh — APPROVED** [review]
All good :)

**Pull request merged**
